project_diet/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.



class Cat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    age = models.IntegerField()
    birthmark = models.CharField(max_length=255)
    medical_condition = models.TextField()
    diet = models.BooleanField(default=False, blank=True)
    diet_description = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ['user', 'name']


class Food(models.Model):
    cat = models.ManyToManyField(Cat)
    company = models.CharField(max_length=64)
    name = models.CharField(max_length=255)

# class Food(models.Model):
#     cat = models.ForeignKey(Cat, on_delete=models.CASCADE)
#     company = models.CharField(max_length=64)
#     name = models.CharField(max_length=255)


class Composition(models.Model):
    food = models.ManyToManyField(Food, through="Content")
    name = models.CharField(max_length=64)


class Content(models.Model):
    quantity = models.IntegerField()
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    composition = models.ForeignKey(Composition, on_delete=models.CASCADE)

project_diet/templates/add_cat.html
{% extends "base.html" %}


{% block description %}

{% endblock %}

{% block content %}

    {{ message|safe }}

    <form method="post">

    {% csrf_token %}

    {{ form.as_p }}

        <br>
    <input type="submit" value="{{ submit }}">

    </form>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script>
    {#$('input[id=id_diet]').attr('checked', false);#}



    var conditional_fields = $("#id_diet_description");

    if ($("#id_diet").prop('checked') == false) {
        conditional_fields.hide();
        $("[for=id_diet_description]").hide();
    }

    $("#id_diet").change(function() {
        console.log($(this), $(this).prop('checked'));
        if ($(this).prop('checked') == true) {
            $("[for=id_diet_description]").show();
            conditional_fields.show();
        } else {
            $("[for=id_diet_description]").hide();
            conditional_fields.hide();
        }
    });
    </script>

    <br>

    <a href="/cats/" class="links_form">Cancel</a>


{% endblock %}

project_diet/templates/base.html
<!doctype html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
        <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!--===============================================================================================-->
    </head>
    <body>
{#        <img src="{% static 'logo.png' %}" alt="piękne logo cl">#}
    	<div class="bg-contact3" style="background-image: url('/static/images/bg-01.jpg');">
		    <div class="container-contact3">
			    <div class="wrap-contact3">
                    {% block description %}{% endblock %}

                    {% block content %} {% endblock %}
                </div>
                <div style="vertical-align: bottom; width:100%">
                {% block footer %}
                    <p>User: {{ request.user }}</p>
                    <p>
                    {% if not request.user.is_authenticated %}
                        <a href="{% url 'login' %}" class="links">Login</a>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="links">Logout</a>
                    {% endif %}
                    <span>|</span>
                    <a href="{% url 'add_user' %}" class="links"> Add new user</a></p>
                    <br><br>
                    <p>version: {{version.0}}.{{version.1}}</p>
                    <p>{{time}}</p>
                {% endblock %}
                </div>
		    </div>
	    </div>
    </body>
</html>

project_diet/templates/c.html
{% extends 'base.html' %}


{% block description %}
    <h2>Composition comparison:</h2>
    <br>
{% endblock %}

{% block content %}

    <style type="text/css">
    .tg  {border-collapse:collapse;border-spacing:0;width: 575px;}
    .tg td{font-family:Poppins-Regular, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
    .tg th{font-family:Poppins-Medium, sans-serif;font-size:16px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:2px;overflow:hidden;word-break:normal;border-color:black;}
    .tg .tg-0lax{text-align:center;vertical-align:top}
    .tg .tg-60hs{font-size:20px;text-align:left;vertical-align:top}
    </style>
    <table class="tg">
        <tr>
            <th class="tg-0lax">Company</th>
            <th class="tg-0lax">Name</th>
            {% for composition in compositions %}

                    <th class="tg-0lax">{{ composition.name }}</th>

            {% endfor %}
        </tr>
        {% for food_quantity in quantity_food_composition %}
                <tr>
                    <td class="tg-0lax">{{ food_quantity.food.company }}</td>
                    <td class="tg-0lax">{{ food_quantity.food.name }}</td>
                    {%  for quantity in food_quantity.quantity %}
                        <td class="tg-0lax">{{ quantity }}</td>
                    {% endfor %}
                </tr>
        {% endfor %}
    </table>

    <br>

    <div><a href="/food_list/{{ cat_id }}" class="links_form">Cancel</a></div>
{% endblock %}

project_diet/templates/cat_data.html
{% extends 'base.html' %}
{% block description %}
    <h2>Data:</h2>
{% endblock %}
{% block content %}
    <ul>
        <li>Name: {{cat.name}}</li>
        <li>Age: {{cat.age}}</li>
        <li>Birthmark: {{cat.birthmark}}</li>
        <li>Medical condition: {{cat.medical_condition}}</li>
        {%  if cat.diet is True %}
        <li>Diet: yes</li>
        <li>Diet description: {{cat.diet_description}}</li>
        {% else %}
            <li>Diet: no</li>
        {% endif %}
    </ul>

    <br>

    <div><a href="/food_list/{{ cat.id }}" class="links_form">Food</a></div>
    <a href="/cats/" class="links_form">Cancel</a>

{% endblock %}

project_diet/templates/cats.html
{% extends 'base.html' %}

{% block description %}
    <h2>List of cats:</h2>
{% endblock %}

{% block content %}
    <ol>
    {% for cat in cats %}
        <li><a href="/cats/{{cat.name}}" class="links_form">{{cat.name}}</a></li>
    {% endfor %}
    </ol>

    <p><a href="{% url 'add_cat' %}" class="links_form">Add cat</a></p>


{% endblock %}

project_diet/templates/comparison.html
{% extends 'base.html' %}


{% block description %}
    <h2>Content comparison:</h2>
    <br>
{% endblock %}

{% block content %}

{#    <style type="text/css">#}
{#    .tg  {border-collapse:collapse;border-spacing:0;width: 575px;}#}
{#    .tg td{font-family:Poppins-Regular, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}#}
{#    .tg th{font-family:Poppins-Medium, sans-serif;font-size:16px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:2px;overflow:hidden;word-break:normal;border-color:black;}#}
{#    .tg .tg-0lax{text-align:center;vertical-align:top}#}
{#    .tg .tg-60hs{font-size:20px;text-align:left;vertical-align:top}#}
{#    </style>#}
    <table class="tg">
        <tr>
            <th class="tg-0lax">Marka</th>
            <th class="tg-0lax">Smak</th>
            <th class="tg-0lax">Składnik</th>
            <th class="tg-0lax">Zawartość w %</th>

        </tr>
        {% for food in food_list %}
            {% for content in food.content_set.all %}
                    <tr>
                        <th class="tg-0lax">{{ food.company }}</th>
                        <th class="tg-0lax">{{ food.name }}</th>
                        <th class="tg-0lax">{{ content.composition.name }}</th>
                        <th class="tg-0lax">{{ content.quantity }}</th>
                    </tr>
            {% endfor %}
        {% endfor %}
    </table>

    <br>

    <div><a href="/food_list/{{ cat_id }}" class="links_form">Cancel</a></div>
{% endblock %}

project_diet/templates/composition_content_list.html
{% extends 'base.html' %}


{% block description %}
    <h2>List of compositions:</h2>
    <br>
{% endblock %}

{% block content %}
    <ul>
    {{ a }}
    {% for composition in compositions %}
        <li>Composition: {{composition.name}}, Percentage content : {{composition.quantity}} %</li>
    {% endfor %}
    </ul>

    <br>

    <a href="{% url 'add_composition' food_id=food_id %}" class="links_form">Add content</a>

    <p><a href="{{request.META.HTTP_REFERER}}" class="links_form">Go back</a></p>

{#        <a href="{% url 'food_list' cat_id=cat_id %}" class="links_form">Testcancel</a>#}

{% endblock %}

project_diet/templates/food_data.html
{% extends 'base.html' %}
{% block description %}
    <h2>Dane:</h2>
{% endblock %}
{% block content %}
    <ul>
        <li>{{food.company}}</li>
        <li>{{food.name}}</li>
    </ul>

    <p><a href="{{request.META.HTTP_REFERER}}">Go back</a></p>


    <a href="{% url 'food_list' cat_id=cat_id %}" class="links_form">testcancel</a>


{% endblock %}

project_diet/templates/food_list.html
{% extends 'base.html' %}


{% block description %}
    <h2>List of companies:</h2>
{% endblock %}

{% block content %}
    <ol>
    {% for food in food_list %}
        <li><a href="/{{ food.id }}/composition" class="links_form">{{food.company}} - {{food.name}}</a></li>
    {% endfor %}
    </ol>


    <p><a href="{% url 'add_food' cat_id=cat_id %}" class="links_form">Add food</a></p>

    <p><a href="{% url 'compare_composition' cat_id=cat_id%}" class="links_form">Composition comparison</a></p>

    <a href="/cats/{{cat_name}}" class="links_form">Cancel</a>

{% endblock %}

project_diet/templates/form.html
{% extends "base.html" %}


{% block description %}
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}


    {{ message|safe }}

    <form method="post" class="uniForm">

    {% csrf_token %}

    {{ form|crispy }}

        <br>

    <div><input type="submit" value="{{ submit }}"></div>

    <br>

    <p><a href="{{request.META.HTTP_REFERER}}" class="links_form">Go back</a></p>


    </form>

{% endblock %}